version: 1.1.{build}
branches:
  only:
  - master
  - develop
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- cmd: dotnet pack src\Neo4j.Map.Extension\Neo4j.Map.Extension.csproj -c Release
artifacts:
- path: src\Neo4j.Map.Extension\bin\release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: RcNwvoW5sxX/JHQuWkz+lRVTgFIG+sxwLSVeCi+/5zBAvx/dl27fVobJpMSGDsbY
  on:
    branch: master
