version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alpha'
  package_version: '{version}-alpha'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet pack src\Neo4j.Map.Extension\Neo4j.Map.Extension.csproj -c Release
artifacts:
- path: src\Neo4j.Map.Extension\bin\release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: RcNwvoW5sxX/JHQuWkz+lRVTgFIG+sxwLSVeCi+/5zBAvx/dl27fVobJpMSGDsbY
